### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by keizo042** [keizo042/mruby-resolv#11]
# TODO

## method

- [ ] `Resolv.getname`
- [ ] `Resolv.getnames`
- [ ] `Resolv.getaddress`
- [ ] `Resolv.getaddresses`
- [ ] `Resolv.each_address`
- [ ] `Resolv.each_name`
- [ ] `Reoslv::DNS.getname`
- [ ] `Reoslv::DNS.getnames`
- [ ] `Resolv::DNS#getname`
- [ ] `Resolv::DNS#getnames`
- [ ] `Resolv::DNS.getaddress`
- [ ] `Resolv::DNS.getaddresses`
- [ ] `Resolv:DNS#getaddress`
- [ ] `Resolv::DNS#getaddresses`
- [ ] `Resolv::DNS.getresource`
- [ ] `Resolv::DNS.getresources`
- [ ] `Resolv::DNS#getresource`
- [ ] `Resolv::DNS#getresources`
- [ ] `Resolv::DNS::Config`

## implementation
- [ ] `Resolv::DNS` accept `resolv.conf`
- [ ] parsing `resolv.conf` to `Resolv::DNS::Conf`
- [x] name offset compression (ref: https://github.com/keizo042/mruby-resolv/issues/6)
- [ ] work with header flags
- [ ] TCP fallback

**Comment by take-cheeze** [comment]
macOS has alias `/etc/resolv.conf` for `/private/etc/resolv.conf`.

**Comment by keizo042** [comment]
in ruby/resolv[1],
`Resolv::DNS.new` accept passed resolv.conf file path as String or equivalent parameter as Hash by arguments.

[1] https://docs.ruby-lang.org/ja/latest/class/Resolv=3a=3aDNS.html#S_NEW

**Comment by keizo042** [comment]
maybe we needs EDNS0 and TCP support for release v1.0.0.
cause of I hear latest RFC require tcp, ad long payload suspected
